// <auto-generated />
using System;
using GeekVault.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GeekVault.Infrastructure.Migrations
{
    [DbContext(typeof(GeekVaultDbContext))]
    [Migration("20250828151319_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GeekVault.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("GeekVault.Domain.Entities.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Alias")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ExtraData")
                        .HasColumnType("text");

                    b.Property<Guid>("FranchiseId")
                        .HasColumnType("uuid");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FranchiseId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("GeekVault.Domain.Entities.CharacterCharacterType", b =>
                {
                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterTypeId")
                        .HasColumnType("uuid");

                    b.HasKey("CharacterId", "CharacterTypeId");

                    b.HasIndex("CharacterTypeId");

                    b.ToTable("CharacterCharacterTypes");
                });

            modelBuilder.Entity("GeekVault.Domain.Entities.CharacterType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CharacterTypes");
                });

            modelBuilder.Entity("GeekVault.Domain.Entities.Franchise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OriginCountry")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Franchises");
                });

            modelBuilder.Entity("GeekVault.Domain.Entities.FranchiseCategory", b =>
                {
                    b.Property<Guid>("FranchiseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.HasKey("FranchiseId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("FranchiseCategories");
                });

            modelBuilder.Entity("GeekVault.Domain.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<int?>("FoundedYear")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("GeekVault.Domain.Entities.TeamMembership", b =>
                {
                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("JoinDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("LeaveDate")
                        .HasColumnType("date");

                    b.Property<string>("RoleInTeam")
                        .HasColumnType("text");

                    b.HasKey("TeamId", "CharacterId");

                    b.HasIndex("CharacterId");

                    b.ToTable("TeamMemberships");
                });

            modelBuilder.Entity("GeekVault.Domain.Entities.Character", b =>
                {
                    b.HasOne("GeekVault.Domain.Entities.Franchise", "Franchise")
                        .WithMany("Characters")
                        .HasForeignKey("FranchiseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Franchise");
                });

            modelBuilder.Entity("GeekVault.Domain.Entities.CharacterCharacterType", b =>
                {
                    b.HasOne("GeekVault.Domain.Entities.Character", "Character")
                        .WithMany("CharacterCharacterTypes")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GeekVault.Domain.Entities.CharacterType", "CharacterType")
                        .WithMany("CharacterCharacterTypes")
                        .HasForeignKey("CharacterTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("CharacterType");
                });

            modelBuilder.Entity("GeekVault.Domain.Entities.FranchiseCategory", b =>
                {
                    b.HasOne("GeekVault.Domain.Entities.Category", "Category")
                        .WithMany("FranchiseCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GeekVault.Domain.Entities.Franchise", "Franchise")
                        .WithMany("FranchiseCategories")
                        .HasForeignKey("FranchiseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Franchise");
                });

            modelBuilder.Entity("GeekVault.Domain.Entities.TeamMembership", b =>
                {
                    b.HasOne("GeekVault.Domain.Entities.Character", "Character")
                        .WithMany("TeamMemberships")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GeekVault.Domain.Entities.Team", "Team")
                        .WithMany("Memberships")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("GeekVault.Domain.Entities.Category", b =>
                {
                    b.Navigation("FranchiseCategories");
                });

            modelBuilder.Entity("GeekVault.Domain.Entities.Character", b =>
                {
                    b.Navigation("CharacterCharacterTypes");

                    b.Navigation("TeamMemberships");
                });

            modelBuilder.Entity("GeekVault.Domain.Entities.CharacterType", b =>
                {
                    b.Navigation("CharacterCharacterTypes");
                });

            modelBuilder.Entity("GeekVault.Domain.Entities.Franchise", b =>
                {
                    b.Navigation("Characters");

                    b.Navigation("FranchiseCategories");
                });

            modelBuilder.Entity("GeekVault.Domain.Entities.Team", b =>
                {
                    b.Navigation("Memberships");
                });
#pragma warning restore 612, 618
        }
    }
}
